Repository bounswe/2021SpringGroup10, pull requests merged in 2021-06, with the labels that each got.

#68 Joke Flask App pull Request
  .gitignore
  Joke_Flask_App/app.py
  Joke_Flask_App/helper_functions.py
  Joke_Flask_App/templates/choice.html
  Joke_Flask_App/templates/home.html
  Joke_Flask_App/templates/make_joke.html
  Joke_Flask_App/templates/show_jokes.html
Labels: Platform: Web, Priority: High, Status: Needs Review, Status: Pending

#84 Test Mechanism of Joke App
  practice_app/app.py
  practice_app/helpers/helper_functions.py
  practice_app/tests/test.py
Labels: Coding: Backend, Priority: Medium, Status: Needs Review, Status: Pending, Type: Enhancement, Type: Test

#67 A simple sportsevents api created. All the required files and a .gitignore file is added.
  .gitignore
  practice_app/app.py
  practice_app/requirements.txt
  practice_app/templates/base.html
  practice_app/templates/index.html
  practice_app/templates/sportevents.html
  practice_app/tests/sportevent_test.py
Labels: Coding: Backend, Coding: Frontend, Platform: Web, Priority: High, Status: Needs Review

#78 Write2us
  practice_app/app.py
  practice_app/requirements.txt
  practice_app/templates/check-my-replies.html
  practice_app/templates/display-messages.html
  practice_app/templates/write2us.html
  practice_app/tests/write2us_test.py
Labels: Coding: Backend, Coding: Frontend, Priority: High

#94 Market app
  practice_app/app.py
  practice_app/templates/home.html
  practice_app/templates/result.html
Labels: Coding: Backend, Coding: Frontend, Platform: Web, Priority: High, Status: In Progress

#96 News app
  .DS_Store
  group10.jfif
  photos
  practice_app/.gitignore
  practice_app/app.py
  practice_app/helpers/helper_functions.py
  practice_app/templates/home.html
  practice_app/templates/index.html
  practice_app/templates/joke_choice.html
  practice_app/templates/joke_home.html
  practice_app/templates/joke_make_joke.html
  practice_app/templates/joke_show_jokes.html
  practice_app/templates/news_base.html
  practice_app/templates/news_index.html
  practice_app/templates/news_pocket.html
  practice_app/tests/news_tests.py
Labels: Coding: Backend, Coding: Frontend, Platform: Web, Status: Needs Review

#69 Weather Api is created, requirements are specified
  .idea/.gitignore
  .idea/2021SpringGroup10.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  practice_app/.DS_Store
Labels: Coding: Backend, Coding: Frontend, Priority: High, Status: Needs Review

#75 Dictionary App
  practice_app/app.py
  practice_app/templates/history.html
  practice_app/templates/result.html
  practice_app/templates/search.html
Labels: Coding: Backend, Coding: Frontend, Platform: Web, Priority: High, Status: In Progress

#103 Unit test of weather api is added
  .DS_Store
  practice_app/.DS_Store
  practice_app/tests/weather_test.py
Labels: Coding: Backend, Priority: High, Status: Needs Review

#102 Write2us bug fix
  .gitignore
  practice_app/app.py
  practice_app/tests/write2us_test.py
Labels: Priority: High, Type: Bug, Type: Test

#104 tests
  practice_app/tests/market_test.py
Labels: Coding: Backend, Priority: High, Status: In Progress, Status: Pending, Type: Enhancement
